name: Create Code And Update Next Version

# 触发器
on:
  push:
    branches:
      - rel

jobs:
  create_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 切换到master分支
        run: |
          git checkout master
          git checkout -
          git rebase master
          git merge master
      - name: 配置git
        run: |
          git config user.name "YCX-Github"
          git config user.email "ycx974577817@gmail.com"
      - name: 安装JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: 生成最新代码
        run: |
          echo "rootProject.name = \"LibDependencies\"" > settings.gradle
          echo "include ':lib'" >> settings.gradle
          bash ./gradlew lib:test --tests "son.ysy.dependencies.Creator.testCreateAll"
      - name: 设置版本环境变量
        run: |
          LIB_VERSION=$(cat lib/version.properties | grep -Po 'VERSION_NAME=\K\d+')
          echo "LIB_VERSION=${LIB_VERSION}" >> $GITHUB_ENV
      - name: 提交生成代码
        run: |
          git add .
          git commit -m "生成${{env.LIB_VERSION}}"
          git push origin rel:release
          git push origin -d rel