name: Create Code And Update Next Version

# 触发器
on:
  push:
    branches:
      - update

jobs:
  create_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 配置git
        run: |
          git config user.name "YCX-Github"
          git config user.email "ycx974577817@gmail.com"
      - name: 设置版本环境变量
        run: |
          LIB_VERSION=$(cat lib/version.properties | grep -Po 'VERSION_NAME=\K\d+')
          echo "LIB_VERSION=${LIB_VERSION}" >> $GITHUB_ENV
      - name: 更新打包版本
        run: |
          LIB_VERSION=${{env.LIB_VERSION}}
          let LIB_VERSION++
          echo "VERSION_NAME=$LIB_VERSION" > lib/version.properties
      - name: 提交版本更新代码
        run: |
          LIB_VERSION=${{env.LIB_VERSION}}
          let LIB_NEXT_VERSION=LIB_VERSION+1
          git add lib/version.properties
          git commit -m "更新发布版本$LIB_VERSION>>$LIB_NEXT_VERSION"
          git push origin update：master
          git push origin -d update